export const GET_JOBS_REQUEST = 'GET_JOBS_REQUEST';
export const GET_JOBS_SUCCESS = 'GET_JOBS_PROCESSED';
export const GET_JOBS_ERROR = 'GET_JOBS_ERROR';
export const FILTER_JOB_TYPES = 'FILTER_JOB_TYPES';
